
const int SCREEN_WIDTH = 23 * 20, SCREEN_HEIGHT = 19 * 20, TILE = 20;

const int CYCLES_PER_SECOND = 200, DELAY_MADE_WHEN_PACMAN_KILLS_A_GHOST = 3, GHOST_MAX_DEFENSIVE_TIME_SECONDS = 8;

const int PACMAN_CYCLES_PER_MOVE = 1, GHOST_AGGRESSIVE_CYCLES_PER_MOVE = 1, GHOST_DEFENSIVE_CYCLES_PER_MOVE = 3;

const int CHEESE_VALUE = 10, CHERRY_VALUE = 100, GHOST_EAT_VALUE = 20;
