#include "models.h"

const int CYCLES_PER_SECOND = 60, DELAY_MADE_WHEN_PACMAN_KILLS_A_GHOST = 5, GHOST_MAX_DEFENSIVE_TIME = 10;

const double PACMAN_NORMAL_SPEED = 1, GHOST_AGGRESSIVE_SPEED = 1, GHOST_DEFENSIVE_SPEED = 0.5;

const int CHEESE_VALUE = 10, CHERRY_VALUE = 100, GHOST_EAT_VALUE = 20;
